import os

def populate():

    add_country(name= "Somalia" , region= "Africa")
    add_country(name= "Angola" , region= "Africa")
    add_country(name= "Argelia" , region= "Africa")
    add_country(name= "Benin" , region= "Africa")
    add_country(name= "Botsuana" , region= "Africa")
    add_country(name= "Burkina Faso" , region= "Africa")
    add_country(name= "Burundi" , region= "Africa")
    add_country(name= "Cabo Verde" , region= "Africa")
    add_country(name= "Camerun" , region= "Africa")
    add_country(name= "Chad" , region= "Africa")
    add_country(name= "Comoras" , region= "Africa")
    add_country(name= "Costa de Marfil" , region= "Africa")
    add_country(name= "Egipto" , region= "Africa")
    add_country(name= "Eritrea" , region= "Africa")
    add_country(name= "Etiopia" , region= "Africa")
    add_country(name= "Gabon" , region= "Africa")
    add_country(name= "Gambia" , region= "Africa")
    add_country(name= "Ghana" , region= "Africa")
    add_country(name= "Guinea" , region= "Africa")
    add_country(name= "Guinea Ecuatorial" , region= "Africa")
    add_country(name= "Guinea-Bisau" , region= "Africa")
    add_country(name= "Kenia" , region= "Africa")
    add_country(name= "Lesoto" , region= "Africa")
    add_country(name= "Liberia" , region= "Africa")
    add_country(name= "Libia" , region= "Africa")
    add_country(name= "Madagascar" , region= "Africa")
    add_country(name= "Malaui" , region= "Africa")
    add_country(name= "Mali" , region= "Africa")
    add_country(name= "Marruecos" , region= "Africa")
    add_country(name= "Mauricio" , region= "Africa")
    add_country(name= "Mauritania" , region= "Africa")
    add_country(name= "Mozambique" , region= "Africa")
    add_country(name= "Namibia" , region= "Africa")
    add_country(name= "Niger" , region= "Africa")
    add_country(name= "Nigeria" , region= "Africa")
    add_country(name= "Republica Centroafricana" , region= "Africa")
    add_country(name= "Republica Democratica del Congo" , region= "Africa")
    add_country(name= "Ruanda" , region= "Africa")
    add_country(name= "Santo Tome y Principe" , region= "Africa")
    add_country(name= "Senegal" , region= "Africa")
    add_country(name= "Seychelles" , region= "Africa")
    add_country(name= "Sierra Leona" , region= "Africa")
    add_country(name= "Suazilandia" , region= "Africa")
    add_country(name= "SudAfrica" , region= "Africa")
    add_country(name= "Sudan del Sur" , region= "Africa")
    add_country(name= "Tanzania" , region= "Africa")
    add_country(name= "Togo" , region= "Africa")
    add_country(name= "Tunez" , region= "Africa")
    add_country(name= "Uganda" , region= "Africa")
    add_country(name= "Yibuti" , region= "Africa")
    add_country(name= "Zambia" , region= "Africa")
    add_country(name= "Zimbabue" , region= "Africa")
    add_country(name= "Republica arabe Saharaui Democratica" , region= "Africa")
    add_country(name= "Republica del Congo" , region= "Africa")
    add_country(name= "Sudan" , region= "Africa")
    add_country(name= "Antigua y Barbuda" , region= "America Central y el Caribe")
    add_country(name= "Bahamas" , region= "America Central y el Caribe")
    add_country(name= "Barbados" , region= "America Central y el Caribe")
    add_country(name= "Belice" , region= "America Central y el Caribe")
    add_country(name= "Costa Rica" , region= "America Central y el Caribe")
    add_country(name= "Cuba" , region= "America Central y el Caribe")
    add_country(name= "El Salvador" , region= "America Central y el Caribe")
    add_country(name= "Granada" , region= "America Central y el Caribe")
    add_country(name= "Guatemala" , region= "America Central y el Caribe")
    add_country(name= "Haiti" , region= "America Central y el Caribe")
    add_country(name= "Honduras" , region= "America Central y el Caribe")
    add_country(name= "Jamaica" , region= "America Central y el Caribe")
    add_country(name= "Nicaragua" , region= "America Central y el Caribe")
    add_country(name= "Panama" , region= "America Central y el Caribe")
    add_country(name= "Republica Dominicana" , region= "America Central y el Caribe")
    add_country(name= "San Cristobal y Nieves" , region= "America Central y el Caribe")
    add_country(name= "San Vicente y las Granadinas" , region= "America Central y el Caribe")
    add_country(name= "Santa Lucia" , region= "America Central y el Caribe")
    add_country(name= "Trinidad y Tobago" , region= "America Central y el Caribe")
    add_country(name= "Anguila" , region= "America Central y el Caribe")
    add_country(name= "Aruba" , region= "America Central y el Caribe")
    add_country(name= "Bermudas" , region= "America Central y el Caribe")
    add_country(name= "Caribe Neerlandes" , region= "America Central y el Caribe")
    add_country(name= "Curazao" , region= "America Central y el Caribe")
    add_country(name= "Dominica" , region= "America Central y el Caribe")
    add_country(name= "Islas Virgenes de los Estados Unidos" , region= "America Central y el Caribe")
    add_country(name= "Puerto Rico" , region= "America Central y el Caribe")
    add_country(name= "Canada" , region= "America del Norte")
    add_country(name= "Estados Unidos" , region= "America del Norte")
    add_country(name= "Groenlandia" , region= "America del Norte")
    add_country(name= "Mexico" , region= "America del Norte")
    add_country(name= "Argentina" , region= "America del Sur")
    add_country(name= "Bolivia" , region= "America del Sur")
    add_country(name= "Brasil" , region= "America del Sur")
    add_country(name= "Chile" , region= "America del Sur")
    add_country(name= "Colombia" , region= "America del Sur")
    add_country(name= "Ecuador" , region= "America del Sur")
    add_country(name= "Guyana" , region= "America del Sur")
    add_country(name= "Paraguay" , region= "America del Sur")
    add_country(name= "Peru" , region= "America del Sur")
    add_country(name= "Surinam" , region= "America del Sur")
    add_country(name= "Uruguay" , region= "America del Sur")
    add_country(name= "Venezuela" , region= "America del Sur")
    add_country(name= "Guayana Francesa" , region= "America del Sur")
    add_country(name= "Birmania" , region= "Asia")
    add_country(name= "Brunei" , region= "Asia")
    add_country(name= "Butan" , region= "Asia")
    add_country(name= "Camboya" , region= "Asia")
    add_country(name= "China" , region= "Asia")
    add_country(name= "Corea del Norte" , region= "Asia")
    add_country(name= "Corea del Sur" , region= "Asia")
    add_country(name= "Filipinas" , region= "Asia")
    add_country(name= "India" , region= "Asia")
    add_country(name= "Indonesia" , region= "Asia")
    add_country(name= "Japon" , region= "Asia")
    add_country(name= "Kazajstan" , region= "Asia")
    add_country(name= "Kirguistan" , region= "Asia")
    add_country(name= "Laos" , region= "Asia")
    add_country(name= "Malasia" , region= "Asia")
    add_country(name= "Maldivas" , region= "Asia")
    add_country(name= "Mongolia" , region= "Asia")
    add_country(name= "Nepal" , region= "Asia")
    add_country(name= "Taiwan" , region= "Asia")
    add_country(name= "Singapur" , region= "Asia")
    add_country(name= "Sri Lanka" , region= "Asia")
    add_country(name= "Tailandia" , region= "Asia")
    add_country(name= "Tayikistan" , region= "Asia")
    add_country(name= "Turkmenistan" , region= "Asia")
    add_country(name= "Uzbekistan" , region= "Asia")
    add_country(name= "Vietnam" , region= "Asia")
    add_country(name= "Banglades" , region= "Asia")
    add_country(name= "Australia" , region= "Australia y Oceania")
    add_country(name= "Fiyi" , region= "Australia y Oceania")
    add_country(name= "Islas Marshall" , region= "Australia y Oceania")
    add_country(name= "Islas Salomon" , region= "Australia y Oceania")
    add_country(name= "Kiribati" , region= "Australia y Oceania")
    add_country(name= "Micronesia" , region= "Australia y Oceania")
    add_country(name= "Nauru" , region= "Australia y Oceania")
    add_country(name= "Nueva Zelanda" , region= "Australia y Oceania")
    add_country(name= "Palaos" , region= "Australia y Oceania")
    add_country(name= "Papua Nueva Guinea" , region= "Australia y Oceania")
    add_country(name= "Samoa" , region= "Australia y Oceania")
    add_country(name= "Timor Oriental" , region= "Australia y Oceania")
    add_country(name= "Tonga" , region= "Australia y Oceania")
    add_country(name= "Tuvalu" , region= "Australia y Oceania")
    add_country(name= "Vanuatu" , region= "Australia y Oceania")
    add_country(name= "Suiza" , region= "Europa")
    add_country(name= "Albania" , region= "Europa")
    add_country(name= "Alemania" , region= "Europa")
    add_country(name= "Andorra" , region= "Europa")
    add_country(name= "Armenia" , region= "Europa")
    add_country(name= "Austria" , region= "Europa")
    add_country(name= "Bielorrusia" , region= "Europa")
    add_country(name= "Bosnia y Herzegovina" , region= "Europa")
    add_country(name= "Bulgaria" , region= "Europa")
    add_country(name= "Chipre" , region= "Europa")
    add_country(name= "Ciudad del Vaticano" , region= "Europa")
    add_country(name= "Croacia" , region= "Europa")
    add_country(name= "Dinamarca" , region= "Europa")
    add_country(name= "Eslovaquia" , region= "Europa")
    add_country(name= "Eslovenia" , region= "Europa")
    add_country(name= "Espana" , region= "Europa")
    add_country(name= "Estonia" , region= "Europa")
    add_country(name= "Finlandia" , region= "Europa")
    add_country(name= "Francia" , region= "Europa")
    add_country(name= "Georgia" , region= "Europa")
    add_country(name= "Grecia" , region= "Europa")
    add_country(name= "Hungria" , region= "Europa")
    add_country(name= "Irlanda" , region= "Europa")
    add_country(name= "Islandia" , region= "Europa")
    add_country(name= "Italia" , region= "Europa")
    add_country(name= "Kosovo" , region= "Europa")
    add_country(name= "Letonia" , region= "Europa")
    add_country(name= "Liechtenstein" , region= "Europa")
    add_country(name= "Lituania" , region= "Europa")
    add_country(name= "Luxemburgo" , region= "Europa")
    add_country(name= "Macedonia" , region= "Europa")
    add_country(name= "Malta" , region= "Europa")
    add_country(name= "Moldavia" , region= "Europa")
    add_country(name= "Monaco" , region= "Europa")
    add_country(name= "Montenegro" , region= "Europa")
    add_country(name= "Noruega" , region= "Europa")
    add_country(name= "Paises Bajos" , region= "Europa")
    add_country(name= "Polonia" , region= "Europa")
    add_country(name= "Portugal" , region= "Europa")
    add_country(name= "Reino Unido" , region= "Europa")
    add_country(name= "Republica Checa" , region= "Europa")
    add_country(name= "Rumania" , region= "Europa")
    add_country(name= "Rusia" , region= "Europa")
    add_country(name= "San Marino" , region= "Europa")
    add_country(name= "Serbia" , region= "Europa")
    add_country(name= "Suecia" , region= "Europa")
    add_country(name= "Ucrania" , region= "Europa")
    add_country(name= "Aland" , region= "Europa")
    add_country(name= "Belgica" , region= "Europa")
    add_country(name= "Gibraltar" , region= "Europa")
    add_country(name= "Afganistan" , region= "Oriente Medio")
    add_country(name= "Arabia Saudita" , region= "Oriente Medio")
    add_country(name= "Azerbaiyan" , region= "Oriente Medio")
    add_country(name= "Barein" , region= "Oriente Medio")
    add_country(name= "Catar" , region= "Oriente Medio")
    add_country(name= "Emiratos arabes Unidos" , region= "Oriente Medio")
    add_country(name= "Irak" , region= "Oriente Medio")
    add_country(name= "Iran" , region= "Oriente Medio")
    add_country(name= "Israel" , region= "Oriente Medio")
    add_country(name= "Jordania" , region= "Oriente Medio")
    add_country(name= "Kuwait" , region= "Oriente Medio")
    add_country(name= "Libano" , region= "Oriente Medio")
    add_country(name= "Oman" , region= "Oriente Medio")
    add_country(name= "Pakistan" , region= "Oriente Medio")
    add_country(name= "Siria" , region= "Oriente Medio")
    add_country(name= "Turquia" , region= "Oriente Medio")
    add_country(name= "Yemen" , region= "Oriente Medio")
    add_country(name= "Palestina" , region= "Oriente Medio")

    
    #print out what we have added
    for c in Country.objects.all():
            print "{0}".format(str(c))



#start execution


def add_country(name,region):
    c = Country.objects.get_or_create(name=name,region=region)[0]
    return c

if __name__ =='__main__':
    print "Starting City population script..."
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'FundacionChile.settings')
    from management.models import Country
    populate()
            

